name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: "This issue  has been open for 60 days with no activity. Add a comment or remove the Stale label to keep open, otherwise it will be close automatically in 7 days."
          stale-pr-message: "This PR has been open for 60 days with no activity. Add a comment or remove the Stale label to keep open, otherwise it will be close automatically in 7 days."
          close-issue-message: "This issue was closed because it has been stalled for 7 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 7 days with no activity."
          stale-issue-label: "no-issue-activity"
          stale-pr-label: "no-pr-activity"
          days-before-stale: 60
          days-before-pr-close: 7
          days-before-issue-close: 7